services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:

  KimaiPlugin\AakSamlBundle\:
    resource: '../../*'
    exclude: '../../{Resources}'

  KimaiPlugin\AakSamlBundle\Repository\AakSamlTeamMetaRepository:
    class:     Doctrine\ORM\EntityRepository
    factory:   ['@doctrine.orm.entity_manager', getRepository]
    arguments: ['KimaiPlugin\AakSamlBundle\Entity\AakSamlTeamMeta']
